### ISSUE TITLE
panic at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by ibotty** [JayceFayne/swayipc-rs#37]
Running a freshly compiled i3status-rust (commit e6ab94b8dc9292e8dd287cd9935f1da79c0d599d) on `sway-1.7-1.fc36.x86_64` with the following configfile get the backtrace below.

```
# cat i3status-rs.conf
[[block]]
block = "focused_window"
max_width = 100

# RUST_BACKTRACE=1 i3status-rs
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'internal error: entered unreachable code', /home/tf/.cargo/registry/src/github.com-1ecc6299db9ec823/swayipc-3.0.0/src/socket.rs:17:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/panicking.rs:48:5
   3: swayipc::socket::get_socketpath
   4: swayipc::connection::Connection::new
   5: <i3status_rs::blocks::focused_window::FocusedWindow as i3status_rs::blocks::ConfigBlock>::new
   6: i3status_rs::blocks::create_block
   7: i3status_rs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

# RUST_BACKTRACE=full i3status-rs
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'internal error: entered unreachable code', /home/tf/.cargo/registry/src/github.com-1ecc6299db9ec823/swayipc-3.0.0/src/socket.rs:17:9
stack backtrace:
   0:     0x55c6cbcfaf0c - std::backtrace_rs::backtrace::libunwind::trace::h793e05efd273d0f4
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55c6cbcfaf0c - std::backtrace_rs::backtrace::trace_unsynchronized::h640b7b86ff610c77
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55c6cbcfaf0c - std::sys_common::backtrace::_print_fmt::h362fa2a4f354f877
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55c6cbcfaf0c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf439e5ed84c74abd
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55c6cbd21f6c - core::fmt::write::h72801a82c94e6ff1
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/fmt/mod.rs:1149:17
   5:     0x55c6cbcf3ae5 - std::io::Write::write_fmt::h5562a8b6da0f0339
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/io/mod.rs:1697:15
   6:     0x55c6cbcfca00 - std::sys_common::backtrace::_print::hb29ddd998d02631c
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55c6cbcfca00 - std::sys_common::backtrace::print::h81965e3d7c90fbb6
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55c6cbcfca00 - std::panicking::default_hook::{{closure}}::h84db205ab6674b38
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:211:50
   9:     0x55c6cbcfc5ab - std::panicking::default_hook::h1bf8bb4159936bca
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:228:9
  10:     0x55c6cbcfd0b4 - std::panicking::rust_panic_with_hook::hf8e86850fbbd03b1
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:606:17
  11:     0x55c6cbcfcb62 - std::panicking::begin_panic_handler::{{closure}}::h590a0d6060ff866e
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:500:13
  12:     0x55c6cbcfb3c4 - std::sys_common::backtrace::__rust_end_short_backtrace::h260b8bd1c848a03c
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55c6cbcfcaf9 - rust_begin_unwind
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:498:5
  14:     0x55c6cb954821 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/panicking.rs:107:14
  15:     0x55c6cb95476d - core::panicking::panic::h50b51d19800453c0
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/panicking.rs:48:5
  16:     0x55c6cbc02352 - swayipc::socket::get_socketpath::ha9e5885bbf65ab36
  17:     0x55c6cbbf76b2 - swayipc::connection::Connection::new::h2b8415b7b1b10efb
  18:     0x55c6cb9e26cf - <i3status_rs::blocks::focused_window::FocusedWindow as i3status_rs::blocks::ConfigBlock>::new::h1edf87a5106445a7
  19:     0x55c6cba824d0 - i3status_rs::blocks::create_block::h60524b548bc30cce
  20:     0x55c6cba37096 - i3status_rs::main::he2ef2ca882f2182a
  21:     0x55c6cbaef7a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdb54f6b045d0f4e6
  22:     0x55c6cbaf0ac9 - std::rt::lang_start::{{closure}}::h4185bddaa65fd2b0
  23:     0x55c6cbcfa751 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h42d3791e66d196c0
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/core/src/ops/function.rs:259:13
  24:     0x55c6cbcfa751 - std::panicking::try::do_call::hc3bcb188e535517f
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:406:40
  25:     0x55c6cbcfa751 - std::panicking::try::hb1edf04d4a7097ab
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:370:19
  26:     0x55c6cbcfa751 - std::panic::catch_unwind::h75ed941ac0d36d57
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panic.rs:133:14
  27:     0x55c6cbcfa751 - std::rt::lang_start_internal::{{closure}}::hc702b3389af4cbea
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/rt.rs:128:48
  28:     0x55c6cbcfa751 - std::panicking::try::do_call::h53276a03c7fe2ebc
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:406:40
  29:     0x55c6cbcfa751 - std::panicking::try::ha9e37f45dc542517
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panicking.rs:370:19
  30:     0x55c6cbcfa751 - std::panic::catch_unwind::h182647595766fee7
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/panic.rs:133:14
  31:     0x55c6cbcfa751 - std::rt::lang_start_internal::h571831ebdba142de
                               at /rustc/c9c4b5d7276297679387189d96a952f2b760e7ad/library/std/src/rt.rs:128:20
  32:     0x55c6cba39002 - main
  33:     0x7f264fbb4590 - __libc_start_call_main
  34:     0x7f264fbb4649 - __libc_start_main_alias_2
  35:     0x55c6cb955005 - _start
  36:                0x0 - <unknown>
```
```

**Comment by ibotty** [comment]
Oh, reading the code I see that the env variable is just not propagated.  Closing.
